name: tarball-60808-becto

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'config-file'
        required: true
        default: '_mkfli4lgit.conf-becto'

permissions:
  contents: write

jobs:
  tarball-60808-becto:
    runs-on: ubuntu-latest
    steps:

      - name: 'install zsh'
        run: sudo apt-get update; sudo apt-get install zsh

      - name: 'install subversion'
        run: sudo apt-get update; sudo apt-get install subversion

      - name: 'install texlive'
        run: sudo apt-get update; sudo apt-get install texlive-latex-base texlive-font-utils texlive-fonts-recommended texlive-fonts-extra lmodern

      - name: 'install texlive / utils'
        run: sudo apt-get update; sudo apt-get install fig2dev latex2html

      - name: 'prepare/check github-runner -> environment'
        run: |
          # cd ${{ github.workspace }}
          # dpkg -l
          echo "TAG_TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +'%Y-%m-%d/%T')" >> $GITHUB_ENV
        shell: zsh {0}

      #- uses: actions/checkout@v4
      #  with:
      #    repository: 'becto-fli4l/fli4l-60808-orig'
      #    ref: 'trunk'
      #    path: 'fli4l-60808-orig'
      #    lfs: 'true'
      #    sparse-checkout: |
      #      bin

      - name: 'get bin/x86_64 from original repo'
        run: |
          cd ${{ github.workspace }}
          mkdir ./bin && cd ./bin
          svn checkout -r60808 https://repo.nettworks.org/svn/fli4l/branches/4.0/trunk/bin/x86_64
        shell: zsh {0}
        
      - uses: actions/checkout@v4
        with:
          repository: 'becto-fli4l/fli4l-60808-becto'
          ref: 'trunk'
          path: 'fli4l-60808-becto'

      #- name: 'prepare/check github-runner -> show workspace'
      #  run: |
      #    cd ${{ github.workspace }}
      #    tree -x -L 3
      #  shell: zsh {0}

      - name: 'create fli4l-60808-becto'
        run: |
          cd ${{ github.workspace }}
          cd ./fli4l-60808-becto && ./_mkfli4lgit.sh ./${{ github.event.inputs.environment }}
        env:
          DEPLOY_ENV: ${{ github.event.inputs.environment }}
        shell: zsh {0}

      - name: 'prepare/check github-runner -> show home'
        run: |
          cd ${{ runner.home }}
          tree -x -L 5
        shell: zsh {0}
        
      - name: 'create tarball-60808-becto /release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG"_"$TAG_TIME" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TAG+$BUILD_TIME" \
        shell: bash
