name: tarball-upstream-becto

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'config-file'
        required: true
        default: '_mkfli4lgit.conf-becto'

permissions:
  contents: write
